import { describe, it, expect } from 'vitest';
import { createHash } from 'node:crypto';
import { readFileSync, existsSync, statSync } from 'node:fs';
import path from 'node:path';

// public/ops/index.html is GENERATED by ops-room/build.js and committed, because
// public/ is what Next serves verbatim and zaostock.com/ops has to return
// something without a build step on the viewer's side.
//
// Committing a generated file invites drift: edit the source, forget to rebuild,
// and the live board silently serves yesterday's day. On the day of the festival
// that is a run of show that disagrees with reality, which is worse than no board
// at all.
//
// So the build stamps a hash of its source into the output, and this test fails
// when the deployed copy was built from a different source than the one in the
// repo. Rebuild with `node ops-room/build.js`.

const ROOT = process.cwd();
const SRC = path.join(ROOT, 'ops-room', 'ops-room.src.html');
const DEPLOYED = path.join(ROOT, 'public', 'ops', 'index.html');

describe('the deployed ops room matches its source', () => {
  it('is actually deployed', () => {
    expect(existsSync(DEPLOYED)).toBe(true);
  });

  it('was built from the source currently in the repo', () => {
    // LF-normalised, matching build.js, so a CRLF checkout and CI agree on the hash.
    const expected = createHash('sha256').update(readFileSync(SRC, 'utf8').replace(/\r\n/g, '\n')).digest('hex').slice(0, 16);
    const stamp = readFileSync(DEPLOYED, 'utf8').match(/name="ops-room-src" content="([a-f0-9]+)"/);
    expect(stamp, 'no source stamp: rebuild with `node ops-room/build.js`').not.toBeNull();
    expect(stamp?.[1], 'ops room is STALE: run `node ops-room/build.js`').toBe(expected);
  });

  it('inlined the marks and photographs rather than linking them', () => {
    // The board has to draw on a phone on a parklet with bad signal. If the
    // images stopped being inlined the page would render blank in exactly the
    // place it is needed most. They are about 400 KB together, which is fine.
    const html = readFileSync(DEPLOYED, 'utf8');
    expect(html).toContain('data:image/png;base64,');
    expect(html).toContain('data:image/jpeg;base64,');
  });

  it('links the theme from /ops/assets/ rather than inlining it', () => {
    // The theme is 3.2 MB of MP3. Inlined as base64 it made the page 4.96 MB
    // and a phone took up to a minute to open it, which is the opposite of a
    // board that works on a parklet. The site copy links it from the same
    // origin instead; the artifact copy (ops-room/ops-room.html, git-ignored)
    // still inlines it because the artifact host blocks media from anywhere
    // else. build.js copies the file into place, so its absence is a build bug.
    const html = readFileSync(DEPLOYED, 'utf8');
    expect(html).not.toContain('data:audio/mpeg;base64,');
    expect(html).toContain('"src":"/ops/assets/zaostock.mp3"');
    expect(existsSync(path.join(ROOT, 'public', 'ops', 'assets', 'zaostock.mp3'))).toBe(true);
  });

  it('stays under the size the build itself budgets for', () => {
    // build.js exits non-zero over 1 MB for the site copy. With the theme
    // linked the page is about half a megabyte; this catches something heavy
    // being inlined again.
    const mb = statSync(DEPLOYED).size / 1048576;
    expect(mb).toBeLessThan(1);
  });
});
